import type {
  AdminSettings,
  PhotoMission,
  Question,
} from "@/lib/types";

export const defaultQuestions: Question[] = [
  {
    type: "mcq",
    id: "q-01",
    title: "1",
    prompt: "נגמרו הפחמים בדיוק כשהמנגל התחיל להתחמם. מה הכי סביר שיקרה עכשיו?",
    options: [
      { id: "a", label: "יעברו ישר לקינוחים בלי לדבר על זה" },
      { id: "b", label: "המנגל ייסגר מיד וכולם ילכו הביתה" },
      { id: "c", label: "ייפתח דיון קצר אך נלהב על מי היה אמור להביא עוד שקית" },
      { id: "d", label: "מישהו יציע לחכות רבע שעה בתקווה שפחמים יופיעו מעצמם" },
    ],
    correctOptionId: "c",
    correctOptionIndex: 2,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-02",
    title: "2",
    prompt: "אתם עומדים בתור ליד מישהו שלא פגשתם קודם. מה הכי סביר שיקרה?",
    options: [
      { id: "a", label: "תוך דקה תגלו מכר משותף, שכונה משותפת או מישהו שמכיר את שניכם" },
      { id: "b", label: "כל אחד יסתכל רק על הטלפון שלו עד סוף הערב" },
      { id: "c", label: "תתנהל שיחה ארוכה בלי לדעת אפילו איך קוראים לו" },
      { id: "d", label: "תעברו לדבר רק על אורך התור כאילו זה נושא הערב המרכזי" },
    ],
    correctOptionId: "a",
    correctOptionIndex: 0,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-03",
    title: "3",
    prompt: "איזה פתיח הכי טבעי לשיחה בין שני אנשים באירוע קהילתי?",
    options: [
      { id: "a", label: "יש לך במקרה טבלת אקסל של כל המשתתפים?" },
      { id: "b", label: "גם אתם מכאן או שבאתם עם מישהו מהמושב?" },
      { id: "c", label: "כמה אחוזי לחות יש היום לדעתך?" },
      { id: "d", label: "באיזה שלב בערב מתחילים בדרך כלל לנתח את מצב החניה?" },
    ],
    correctOptionId: "b",
    correctOptionIndex: 1,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-04",
    title: "4",
    prompt: "מה בדרך כלל קורה כשכמה ילדים שלא מכירים מתחילים לשחק יחד?",
    options: [
      { id: "a", label: "כל אחד שומר על הפינה שלו ולא מתקרב לאחרים" },
      { id: "b", label: "מישהו פותח ישיבת היכרות רשמית לפני שמתחילים" },
      { id: "c", label: "הם ממתינים שמבוגר יכריז מה מותר ומה אסור" },
      { id: "d", label: "אחרי רגע הם כבר ממציאים משחק עם חוקים שרק הם מבינים" },
    ],
    correctOptionId: "d",
    correctOptionIndex: 3,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-05",
    title: "5",
    prompt: "אמרו לכם להביא 'משהו קטן' למפגש. מה הכי סביר שתביאו בפועל?",
    options: [
      { id: "a", label: "מגש שמספיק ליותר אנשים ממה שתכננתם, רק ליתר ביטחון" },
      { id: "b", label: "עוגייה אחת אישית כי לא רציתם להגזים" },
      { id: "c", label: "רק מפיות כדי לא לבלוט" },
      { id: "d", label: "צלחת יפה וריקה מתוך אמונה שמישהו כבר ימלא אותה" },
    ],
    correctOptionId: "a",
    correctOptionIndex: 0,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-06",
    title: "6",
    prompt: "מה הכי סביר שיקרה ליד שולחן הכיבוד חמש דקות אחרי שפותחים אותו?",
    options: [
      { id: "a", label: "כולם יעמדו במרחק מנומס ויחכו שמישהו אחר יתחיל" },
      { id: "b", label: "אף אחד לא ייגש עד שתהיה הכרזה עם מיקרופון" },
      { id: "c", label: "יישמע 'אני רק טועם', בזמן שהצלחות כבר מתחילות להתמלא" },
      { id: "d", label: "מישהו יתחיל לחלק תפקידים כמו מנהל תנועה של סלטים" },
    ],
    correctOptionId: "c",
    correctOptionIndex: 2,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-07",
    title: "7",
    prompt: "מישהו אומר 'אני רק שואל'. למה כדאי להתכונן?",
    options: [
      { id: "a", label: "לשאלה אחת קצרה שאפשר לענות עליה בכן או לא" },
      { id: "b", label: "לשיחה שתכלול עוד כמה שאלות המשך וגם סיפור קטן" },
      { id: "c", label: "לבקשה לחתימה על מסמך רשמי" },
      { id: "d", label: "להסבר מלא עם תרשים זרימה ומסקנות ביניים" },
    ],
    correctOptionId: "b",
    correctOptionIndex: 1,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-08",
    title: "8",
    prompt: "מישהו מבקש להצטרף לשולחן שלכם. מה התגובה הכי טבעית באירוע כזה?",
    options: [
      { id: "a", label: "להציע לו לעמוד לידכם עד שיתפנה מקום" },
      { id: "b", label: "לשלוח אותו לשולחן ועדת הקבלה" },
      { id: "c", label: "לשאול קודם אם יש לו המלצות על הקינוחים" },
      { id: "d", label: "להזיז כיסאות, לפתוח מקום ולהגיד לו לשבת בכיף" },
    ],
    correctOptionId: "d",
    correctOptionIndex: 3,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-09",
    title: "9",
    prompt: "מה הכי מחבר בין אנשים באירוע קהילתי מוצלח?",
    options: [
      { id: "a", label: "רגע של שיחה אמיתית עם מישהו שלא הכרתם קודם" },
      { id: "b", label: "לוח זמנים מדויק ברמת הדקה" },
      { id: "c", label: "טופס משוב שמחולק בכניסה" },
      { id: "d", label: "הכרזה כל רבע שעה שהאירוע מתקדם יפה" },
    ],
    correctOptionId: "a",
    correctOptionIndex: 0,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-10",
    title: "10",
    prompt: "איזה משפט הכי סביר לשמוע בסוף ערב מוצלח?",
    options: [
      { id: "a", label: "מעניין אם זה עומד בתקן אירועים" },
      { id: "b", label: "חייבים לעשות את זה שוב, רק בלי לחכות עד השנה הבאה" },
      { id: "c", label: "אני עדיין לא בטוח שהיה מספיק מקום ליד הסלטים" },
      { id: "d", label: "רגע, מישהו ספר כבר כמה שיחות נפתחו ליד העוגות?" },
    ],
    correctOptionId: "b",
    correctOptionIndex: 1,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-11",
    title: "11",
    prompt: "מה הכי סביר שיקרה בקבוצת הוואטסאפ של היישוב אחרי האירוע?",
    options: [
      { id: "a", label: "רק הודעת תודה אחת קצרה ותו לא" },
      { id: "b", label: "הקבוצה תיסגר עד האירוע הבא" },
      { id: "c", label: "מישהו יכתוב תודה, ואז יתחיל שרשור של תמונות, השלמות ותזכורות" },
      { id: "d", label: "תיפתח הצבעה מסודרת על המנה הכי פופולרית" },
    ],
    correctOptionId: "c",
    correctOptionIndex: 2,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-12",
    title: "12",
    prompt: "מישהו אומר 'תקפצו אלינו לקפה'. מה הפירוש הכי מציאותי?",
    options: [
      { id: "a", label: "מפגש של שבע דקות בדיוק" },
      { id: "b", label: "רק כוס קפה אחת בעמידה, בלי לשבת" },
      { id: "c", label: "פגישה קצרה שבה כולם יישארו מאוד ממוקדים" },
      { id: "d", label: "קפה, שיחה, וכנראה גם משהו מתוק, כלומר יותר זמן ממה שחשבתם" },
    ],
    correctOptionId: "d",
    correctOptionIndex: 3,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-13",
    title: "13",
    prompt: "ראיתם תור ארוך ליד דוכן פופולרי. מה הכי סביר שמישהו ישאל?",
    options: [
      { id: "a", label: "אפשר לעזור איכשהו כדי לזרז את התהליך?" },
      { id: "b", label: "מה מחלקים פה שכולם מחכים ככה?" },
      { id: "c", label: "יש דוח מסודר על זמני ההמתנה?" },
      { id: "d", label: "באיזה שלב התור הזה נהיה מוקד משיכה?" },
    ],
    correctOptionId: "b",
    correctOptionIndex: 1,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-14",
    title: "14",
    prompt: "מה הכי עוזר לאדם חדש להרגיש שייך מהר באירוע כזה?",
    options: [
      { id: "a", label: "להכיר לו אנשים, לשתף אותו, ולדבר איתו בגובה העיניים" },
      { id: "b", label: "לתת לו לעמוד לבד עד שהוא יתרגל" },
      { id: "c", label: "להסביר לו קודם את כל החוקים הטכניים" },
      { id: "d", label: "להבטיח לו שאחרי שעה הכול ירגיש טבעי יותר" },
    ],
    correctOptionId: "a",
    correctOptionIndex: 0,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-15",
    title: "15",
    prompt: "מישהו אומר 'אני רק טועם'. מה הכי סביר שיקרה שנייה אחר כך?",
    options: [
      { id: "a", label: "הוא יעבור הלאה בלי לגעת בכלום" },
      { id: "b", label: "הוא יתנצל ויבקש רק חצי טעימה" },
      { id: "c", label: "הטעימה תתרחב לעוד שתיים או שלוש בדיקות איכות קטנות" },
      { id: "d", label: "הוא יתחיל לנהל רישום מסודר של כל מה שטעם" },
    ],
    correctOptionId: "c",
    correctOptionIndex: 2,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-16",
    title: "16",
    prompt: "מה הכי סביר שיקרה כשילד מסביר למבוגר איך משהו עובד?",
    options: [
      { id: "a", label: "המבוגר יעביר מיד את הנושא הלאה" },
      { id: "b", label: "יבקשו חוות דעת משלושה מבוגרים נוספים לפני שמקשיבים" },
      { id: "c", label: "המבוגר ינסה לנחש לבד ורק אז ישאל" },
      { id: "d", label: "המבוגר יקשיב ברצינות כאילו קיבל הדרכה ממומחה" },
    ],
    correctOptionId: "d",
    correctOptionIndex: 3,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-17",
    title: "17",
    prompt: "ביקשו עזרה קטנה בהרמת ציוד. מה הכי סביר שיקרה?",
    options: [
      { id: "a", label: "תוך רגע יצטרפו עוד שניים והעניין יהפוך למבצע משותף" },
      { id: "b", label: "כולם יעשו כאילו לא שמעו" },
      { id: "c", label: "ייפתח דיון ארוך על הדרך הנכונה להרים" },
      { id: "d", label: "מישהו יקים ועדת תיאום קטנה לפני שנוגעים בציוד" },
    ],
    correctOptionId: "a",
    correctOptionIndex: 0,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-18",
    title: "18",
    prompt: "מה הכי סביר שיקרה כשמישהו מתחיל לספר סיפור מצחיק על אירוע קודם?",
    options: [
      { id: "a", label: "כולם יבקשו לשמוע את זה רק בכתב" },
      { id: "b", label: "מישהו יוסיף פרט, ואז עוד מישהו יתקן אותו בחיוך" },
      { id: "c", label: "השיחה תיעצר כדי לאמת תאריכים" },
      { id: "d", label: "מישהו יכריז שצריך לפתוח תיק מסודר על הסיפור" },
    ],
    correctOptionId: "b",
    correctOptionIndex: 1,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-19",
    title: "19",
    prompt: "מה הכי עוזר לאנשים להישאר באירוע יותר זמן ממה שתכננו?",
    options: [
      { id: "a", label: "שעון גדול שמזכיר להם את השעה" },
      { id: "b", label: "כיסאות מסודרים בשורה" },
      { id: "c", label: "הבטחה שכולם יקבלו תזכורת מתי ללכת" },
      { id: "d", label: "שיחה טובה או חיבור נעים שלא מתחשק לקטוע באמצע" },
    ],
    correctOptionId: "d",
    correctOptionIndex: 3,
    basePoints: 100,
  },
  {
    type: "mcq",
    id: "q-20",
    title: "20",
    prompt: "מה באמת מחבר בין כל האנשים כאן הערב?",
    options: [
      { id: "a", label: "בעיקר רשימת ההפעלה של הערב" },
      { id: "b", label: "זה שלכולם בדיוק אותו טעם" },
      { id: "c", label: "התחושה שאפשר להכיר, לצחוק ולחגוג יחד" },
      { id: "d", label: "זה שכולם עברו במקרה ליד אותו דוכן" },
    ],
    correctOptionId: "c",
    correctOptionIndex: 2,
    basePoints: 100,
  },
];

export const defaultMissions: PhotoMission[] = [
  {
    type: "photo",
    id: "m-01",
    title: "משימה 1",
    prompt: 'מצאו מישהו שלא הגעתם איתו, עשו יחד סלפי "עצמאות שמח"',
    basePoints: 250,
  },
  {
    type: "photo",
    id: "m-02",
    title: "משימה 2",
    prompt: "צלמו תמונה של שלושה דורות שונים יחד",
    basePoints: 250,
  },
  {
    type: "photo",
    id: "m-03",
    title: "משימה 3",
    prompt: "מצאו מישהו שלא דיברתם איתו קודם, גלו מה המאכל האהוב עליו, והצטלמו יחד",
    basePoints: 250,
  },
  {
    type: "photo",
    id: "m-04",
    title: "משימה 4",
    prompt: 'צלמו תמונה עם מישהו שלבוש הכי "עצמאות" בעיניכם',
    basePoints: 250,
  },
  {
    type: "photo",
    id: "m-05",
    title: "משימה 5",
    prompt: "מצאו זוג או משפחה אחרת, החליפו ביניכם פריט קטן, והצטלמו יחד",
    basePoints: 250,
  },
  {
    type: "photo",
    id: "m-06",
    title: "משימה 6",
    prompt: "בקשו ממישהו מבוגר טיפ לחיים והצטלמו יחד אחרי ששמעתם אותו",
    basePoints: 250,
  },
  {
    type: "photo",
    id: "m-07",
    title: "משימת סיום",
    prompt: 'צלמו תמונה קבוצתית עם כמה שיותר אנשים שלא הגעתם איתם וכתבו: "זה מה שמחבר בינינו"',
    basePoints: 400,
    isFinal: true,
  },
];

export const defaultAdminSettings: AdminSettings = {
  introText:
    "כוכבניק - סקר הכי ישראלי שיש. עונים, מצלמים, ובסוף מגלים איך כל הקהילה בחרה.",
  prizeLabels: {
    first: "",
    second: "",
    third: "",
  },
  globalSoundEnabled: true,
};
